spring.application.name=api

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/fo}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# Cors
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

# JWT
jwt.public-key=classpath:keys/public.pem
jwt.private-key=classpath:keys/private.pem
jwt.duration=86400
